### ISSUE TITLE
Show connection notification only for a specific screen

### ISSUE THREAD

**Issue by cyb3rsalih** [AmrAbdelmagid/connection_notifier#1]
Hi! Thank you for this awesome package.

I have an app that need internet only one tab. When I add the `ConnectionNotifier` to root of app,
the disconnect notification appears whole app.

Is it possible to use it only for one screen?

When I removed from root and place the screen I want, toggling  keyboard breaks the screen.

Is there any solution for this? 
<img width="439" alt="Screen Shot 2022-12-29 at 12 25 24" src="https://user-images.githubusercontent.com/17196669/209931291-d192968f-87f5-45f6-b033-68413f914cc4.png">

**Comment by AmrAbdelmagid** [comment]
Thanks @cyb3rsalih for opening an issue.
 `ConnectionNotifier`  should be used on the root of the app, but I will try to add this functionality soon to be able to use this effect on a specific screen only.

**Comment by AmrAbdelmagid** [comment]
@cyb3rsalih I'm sorry as it is late, but now `LocalConenctionNotifier` is available. Thanks!
